import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "./services/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next Hero",
    template: "%s | Next Hero",
  },
  description: "Generated by create next app",
};
// export const metadata = {
//   title: "Next Hero",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          <div className=''>{children}</div>
          <footer className='bg-blue-400'>This is my footer</footer>
        </body>
      </AuthProvider>
    </html>
  );
}
